language: ruby
rvm:
- 2.0.0
- 1.9.3
- 1.8.7
- rbx-19mode
- jruby-19mode
- jruby-18mode

branches:
  except: [".."]
  only: ["master"]

env:
  - "rack=master"
  - "rack=1.3.4"

script: make test
before_script: make pretest
after_script:  make clean

before_script:
  - make pretest1
  - make pretest2